import { useEffect, useMemo, useState } from "react";
import { ExternalLink, Loader2, Save } from "lucide-react";
import { Btn, PageHead } from "@/components/admin/AdminUI";
import { getAdminProgramSalesPages, saveAdminProgramSalesPage } from "@/lib/program-sales.functions";

type Step = { phase: string; title: string; description: string };
type SalesDraft = { landingEyebrow:string; landingHeadline:string; landingSummary:string; landingWhyHeadline:string; landingBenefit1:string; landingBenefit2:string; landingBenefit3:string; landingAudience:string; landingReassurance:string; techniqueEyebrow:string; techniqueHeadline:string; techniqueBody:string; curriculum:Step[]; finalHeadline:string };
type Video = Partial<SalesDraft> & { id:string; title:string; description?:string; curriculum?:Step[] };
const control = "min-h-11 w-full border border-border bg-background px-3 py-2 text-sm leading-relaxed outline-none focus:border-ink";
const textarea = `${control} min-h-24 resize-y`;
const fallbackSteps: Step[] = [{phase:"Inhibit",title:"Reduce unnecessary tension",description:"Use targeted techniques for muscles that are working harder than needed."},{phase:"Activate",title:"Build local control",description:"Practise deliberate control without unnecessary substitution."},{phase:"Integrate",title:"Connect the full pattern",description:"Bring the new option back into coordinated movement."}];
function makeDraft(v:Video,s?:Partial<SalesDraft>):SalesDraft { const b:SalesDraft={landingEyebrow:v.landingEyebrow||"Targeted movement session",landingHeadline:v.landingHeadline||v.title,landingSummary:v.landingSummary||v.description||"",landingWhyHeadline:v.landingWhyHeadline||"Turn the theory into a sequence you can follow.",landingBenefit1:v.landingBenefit1||"",landingBenefit2:v.landingBenefit2||"",landingBenefit3:v.landingBenefit3||"",landingAudience:v.landingAudience||"",landingReassurance:v.landingReassurance||"One payment gives you protected access through your personal movement library.",techniqueEyebrow:"Why technique matters",techniqueHeadline:"Knowing what to do is one thing. Knowing how to achieve it is another.",techniqueBody:"This session teaches a focused technique, then places it inside a clear progression you can follow.",curriculum:v.curriculum?.length===3?v.curriculum:fallbackSteps,finalHeadline:"Put the method into practice."}; return {...b,...s,curriculum:s?.curriculum?.length===3?s.curriculum:b.curriculum}; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="mb-4 block"><span className="mb-2 block font-mono text-[10px] uppercase tracking-[.18em] opacity-70">{label}</span>{children}</label>; }

export function ProgramSalesPageEditor(){
 const [videos,setVideos]=useState<Video[]>([]),[records,setRecords]=useState<Record<string,Partial<SalesDraft>>>({}); const [videoId,setVideoId]=useState(""),[draft,setDraft]=useState<SalesDraft|null>(null); const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{void Promise.all([fetch("/assets/data/videos.json",{cache:"no-store"}).then(r=>r.json()),getAdminProgramSalesPages()]).then(([catalog,saved])=>{const list=(catalog as Video[]).filter(v=>v?.id);setVideos(list);setRecords(Object.fromEntries(saved.map(r=>[r.video_id,r.content as Partial<SalesDraft>])));setVideoId(list[0]?.id||"");}).catch(e=>setMessage(e instanceof Error?e.message:String(e))).finally(()=>setLoading(false));},[]);
 const video=useMemo(()=>videos.find(v=>v.id===videoId),[videos,videoId]); useEffect(()=>{if(video)setDraft(makeDraft(video,records[video.id]));},[video,records]);
 const set=(key:keyof SalesDraft,value:string)=>setDraft(d=>d?{...d,[key]:value}:d); const setStep=(i:number,key:keyof Step,value:string)=>setDraft(d=>d?{...d,curriculum:d.curriculum.map((x,n)=>n===i?{...x,[key]:value}:x)}:d);
 async function save(){if(!draft||!videoId)return;setSaving(true);setMessage("");try{const r=await saveAdminProgramSalesPage({data:{videoId,content:draft}});setRecords(x=>({...x,[videoId]:r.content as Partial<SalesDraft>}));setMessage("Sales page published. The public page will update automatically.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setSaving(false);}}
 if(loading)return <div className="flex min-h-80 items-center justify-center gap-2"><Loader2 className="h-4 w-4 animate-spin"/>Loading sales pages…</div>;
 return <div className="mx-auto max-w-7xl px-5 py-6 lg:px-8"><PageHead title="Sales page editor" meta="Edit the page in the same order visitors read it." actions={<div className="flex gap-2"><a className="inline-flex min-h-11 items-center gap-2 border border-border px-4 py-3 text-sm font-bold" href={`/video.html?id=${videoId}`} target="_blank" rel="noreferrer">Open live page <ExternalLink className="h-4 w-4"/></a><Btn variant="ink" onClick={save} disabled={!draft||saving}>{saving?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Save className="mr-2 h-4 w-4"/>}Publish changes</Btn></div>}/>
 <div className="mt-5 border border-border bg-card p-4"><label className="text-xs font-bold uppercase tracking-widest">Program sales page</label><select className={`${control} mt-2 max-w-md`} value={videoId} onChange={e=>setVideoId(e.target.value)}>{videos.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select>{message&&<p className="mt-3 text-sm">{message}</p>}</div>
 {draft&&<div className="mt-5 overflow-hidden border border-border bg-card"><section className="grid bg-ink text-ink-foreground lg:grid-cols-[1.15fr_.85fr]"><div className="p-6 lg:p-10"><Field label="Eyebrow"><input className={control} value={draft.landingEyebrow} onChange={e=>set("landingEyebrow",e.target.value)}/></Field><Field label="Main headline"><textarea className={`${textarea} min-h-32 text-2xl font-black`} value={draft.landingHeadline} onChange={e=>set("landingHeadline",e.target.value)}/></Field></div><div className="p-6 lg:p-10"><Field label="Opening summary"><textarea className={`${textarea} min-h-40`} value={draft.landingSummary} onChange={e=>set("landingSummary",e.target.value)}/></Field></div></section>
 <section className="p-6 lg:p-10"><Field label="Why this session"><input className={`${control} text-xl font-bold`} value={draft.landingWhyHeadline} onChange={e=>set("landingWhyHeadline",e.target.value)}/></Field><div className="mt-4 grid gap-3 lg:grid-cols-3">{(["landingBenefit1","landingBenefit2","landingBenefit3"] as const).map((k,i)=><Field key={k} label={`Benefit ${i+1}`}><textarea className={textarea} value={draft[k]} onChange={e=>set(k,e.target.value)}/></Field>)}</div></section>
 <section className="border-y border-border bg-secondary p-6 lg:p-10"><Field label="Technique eyebrow"><input className={control} value={draft.techniqueEyebrow} onChange={e=>set("techniqueEyebrow",e.target.value)}/></Field><Field label="Technique headline"><input className={`${control} text-xl font-bold`} value={draft.techniqueHeadline} onChange={e=>set("techniqueHeadline",e.target.value)}/></Field><Field label="Technique explanation"><textarea className={textarea} value={draft.techniqueBody} onChange={e=>set("techniqueBody",e.target.value)}/></Field></section>
 <section className="p-6 lg:p-10"><p className="mb-4 text-xs font-bold uppercase tracking-widest">Three-phase curriculum</p><div className="grid gap-3 lg:grid-cols-3">{draft.curriculum.map((s,i)=><div key={i} className="border border-border p-4"><input className={control} value={s.phase} onChange={e=>setStep(i,"phase",e.target.value)}/><input className={`${control} mt-2 font-bold`} value={s.title} onChange={e=>setStep(i,"title",e.target.value)}/><textarea className={`${textarea} mt-2`} value={s.description} onChange={e=>setStep(i,"description",e.target.value)}/></div>)}</div></section>
 <section className="grid border-t border-border lg:grid-cols-2"><div className="p-6 lg:p-10"><Field label="Who this is for"><textarea className={textarea} value={draft.landingAudience} onChange={e=>set("landingAudience",e.target.value)}/></Field></div><div className="bg-accent p-6 text-accent-foreground lg:p-10"><Field label="Purchase reassurance"><textarea className={textarea} value={draft.landingReassurance} onChange={e=>set("landingReassurance",e.target.value)}/></Field><Field label="Closing headline"><input className={`${control} font-bold`} value={draft.finalHeadline} onChange={e=>set("finalHeadline",e.target.value)}/></Field></div></section></div>}
 </div>;
}
