/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MovementCheckRouteImport } from './routes/movement-check'
import { Route as MusclesRouteImport } from './routes/muscles'
import { Route as Ver1RouteImport } from './routes/ver1'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminGuidesRouteImport } from './routes/admin.guides'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as ApiCloudflareStreamWebhookRouteImport } from './routes/api/cloudflare-stream-webhook'
import { Route as CheckoutCompleteRouteImport } from './routes/checkout.complete'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryProgramSlugRouteImport } from './routes/library.$programSlug'
import { Route as LibraryAccountRouteImport } from './routes/library.account'
import { Route as MusclesIndexRouteImport } from './routes/muscles.index'
import { Route as MusclesMuscleIdRouteImport } from './routes/muscles.$muscleId'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as Ver1IndexRouteImport } from './routes/ver1.index'
import { Route as Ver1AdminRouteImport } from './routes/ver1.admin'
import { Route as AdminMusclesIndexRouteImport } from './routes/admin.muscles.index'
import { Route as AdminMusclesMuscleIdRouteImport } from './routes/admin.muscles.$muscleId'
import { Route as AdminMusclesImportRouteImport } from './routes/admin.muscles.import'
import { Route as AdminRecipesIndexRouteImport } from './routes/admin.recipes.index'
import { Route as AdminRecipesRecipeIdRouteImport } from './routes/admin.recipes.$recipeId'
import { Route as AdminRecipesImportRouteImport } from './routes/admin.recipes.import'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api.public.paddle-webhook'
import { Route as Ver1AdminSplatRouteImport } from './routes/ver1.admin.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementCheckRoute = MovementCheckRouteImport.update({
  id: '/movement-check',
  path: '/movement-check',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesRoute = MusclesRouteImport.update({
  id: '/muscles',
  path: '/muscles',
  getParentRoute: () => rootRouteImport,
} as any)
const Ver1Route = Ver1RouteImport.update({
  id: '/ver1',
  path: '/ver1',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidesRoute = AdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCloudflareStreamWebhookRoute =
  ApiCloudflareStreamWebhookRouteImport.update({
    id: '/api/cloudflare-stream-webhook',
    path: '/api/cloudflare-stream-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutCompleteRoute = CheckoutCompleteRouteImport.update({
  id: '/checkout/complete',
  path: '/checkout/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryProgramSlugRoute = LibraryProgramSlugRouteImport.update({
  id: '/$programSlug',
  path: '/$programSlug',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryAccountRoute = LibraryAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LibraryRoute,
} as any)
const MusclesIndexRoute = MusclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MusclesRoute,
} as any)
const MusclesMuscleIdRoute = MusclesMuscleIdRouteImport.update({
  id: '/$muscleId',
  path: '/$muscleId',
  getParentRoute: () => MusclesRoute,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Ver1IndexRoute = Ver1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Ver1Route,
} as any)
const Ver1AdminRoute = Ver1AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => Ver1Route,
} as any)
const AdminMusclesIndexRoute = AdminMusclesIndexRouteImport.update({
  id: '/muscles/',
  path: '/muscles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMusclesMuscleIdRoute = AdminMusclesMuscleIdRouteImport.update({
  id: '/muscles/$muscleId',
  path: '/muscles/$muscleId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMusclesImportRoute = AdminMusclesImportRouteImport.update({
  id: '/muscles/import',
  path: '/muscles/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesIndexRoute = AdminRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRecipeIdRoute = AdminRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesImportRoute = AdminRecipesImportRouteImport.update({
  id: '/recipes/import',
  path: '/recipes/import',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle-webhook',
  path: '/api/public/paddle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const Ver1AdminSplatRoute = Ver1AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => Ver1AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/movement-check': typeof MovementCheckRoute
  '/muscles': typeof MusclesRouteWithChildren
  '/ver1': typeof Ver1RouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/api/cloudflare-stream-webhook': typeof ApiCloudflareStreamWebhookRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/library/$programSlug': typeof LibraryProgramSlugRoute
  '/library/account': typeof LibraryAccountRoute
  '/muscles/$muscleId': typeof MusclesMuscleIdRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/ver1/admin': typeof Ver1AdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/muscles/': typeof MusclesIndexRoute
  '/ver1/': typeof Ver1IndexRoute
  '/admin/muscles/$muscleId': typeof AdminMusclesMuscleIdRoute
  '/admin/muscles/import': typeof AdminMusclesImportRoute
  '/admin/recipes/$recipeId': typeof AdminRecipesRecipeIdRoute
  '/admin/recipes/import': typeof AdminRecipesImportRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/ver1/admin/$': typeof Ver1AdminSplatRoute
  '/admin/muscles/': typeof AdminMusclesIndexRoute
  '/admin/recipes/': typeof AdminRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movement-check': typeof MovementCheckRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/api/cloudflare-stream-webhook': typeof ApiCloudflareStreamWebhookRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/library/$programSlug': typeof LibraryProgramSlugRoute
  '/library/account': typeof LibraryAccountRoute
  '/muscles/$muscleId': typeof MusclesMuscleIdRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/ver1/admin': typeof Ver1AdminRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/library': typeof LibraryIndexRoute
  '/muscles': typeof MusclesIndexRoute
  '/ver1': typeof Ver1IndexRoute
  '/admin/muscles/$muscleId': typeof AdminMusclesMuscleIdRoute
  '/admin/muscles/import': typeof AdminMusclesImportRoute
  '/admin/recipes/$recipeId': typeof AdminRecipesRecipeIdRoute
  '/admin/recipes/import': typeof AdminRecipesImportRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/ver1/admin/$': typeof Ver1AdminSplatRoute
  '/admin/muscles': typeof AdminMusclesIndexRoute
  '/admin/recipes': typeof AdminRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/movement-check': typeof MovementCheckRoute
  '/muscles': typeof MusclesRouteWithChildren
  '/ver1': typeof Ver1RouteWithChildren
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/api/cloudflare-stream-webhook': typeof ApiCloudflareStreamWebhookRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/library/$programSlug': typeof LibraryProgramSlugRoute
  '/library/account': typeof LibraryAccountRoute
  '/muscles/$muscleId': typeof MusclesMuscleIdRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/ver1/admin': typeof Ver1AdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/muscles/': typeof MusclesIndexRoute
  '/ver1/': typeof Ver1IndexRoute
  '/admin/muscles/$muscleId': typeof AdminMusclesMuscleIdRoute
  '/admin/muscles/import': typeof AdminMusclesImportRoute
  '/admin/recipes/$recipeId': typeof AdminRecipesRecipeIdRoute
  '/admin/recipes/import': typeof AdminRecipesImportRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/ver1/admin/$': typeof Ver1AdminSplatRoute
  '/admin/muscles/': typeof AdminMusclesIndexRoute
  '/admin/recipes/': typeof AdminRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/library'
    | '/movement-check'
    | '/muscles'
    | '/ver1'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/guides'
    | '/admin/lessons'
    | '/admin/orders'
    | '/admin/programs'
    | '/api/cloudflare-stream-webhook'
    | '/checkout/complete'
    | '/guides/$slug'
    | '/library/$programSlug'
    | '/library/account'
    | '/muscles/$muscleId'
    | '/recipes/$slug'
    | '/ver1/admin'
    | '/admin/'
    | '/library/'
    | '/muscles/'
    | '/ver1/'
    | '/admin/muscles/$muscleId'
    | '/admin/muscles/import'
    | '/admin/recipes/$recipeId'
    | '/admin/recipes/import'
    | '/api/public/paddle-webhook'
    | '/ver1/admin/$'
    | '/admin/muscles/'
    | '/admin/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movement-check'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/guides'
    | '/admin/lessons'
    | '/admin/orders'
    | '/admin/programs'
    | '/api/cloudflare-stream-webhook'
    | '/checkout/complete'
    | '/guides/$slug'
    | '/library/$programSlug'
    | '/library/account'
    | '/muscles/$muscleId'
    | '/recipes/$slug'
    | '/ver1/admin'
    | '/admin'
    | '/library'
    | '/muscles'
    | '/ver1'
    | '/admin/muscles/$muscleId'
    | '/admin/muscles/import'
    | '/admin/recipes/$recipeId'
    | '/admin/recipes/import'
    | '/api/public/paddle-webhook'
    | '/ver1/admin/$'
    | '/admin/muscles'
    | '/admin/recipes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/library'
    | '/movement-check'
    | '/muscles'
    | '/ver1'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/guides'
    | '/admin/lessons'
    | '/admin/orders'
    | '/admin/programs'
    | '/api/cloudflare-stream-webhook'
    | '/checkout/complete'
    | '/guides/$slug'
    | '/library/$programSlug'
    | '/library/account'
    | '/muscles/$muscleId'
    | '/recipes/$slug'
    | '/ver1/admin'
    | '/admin/'
    | '/library/'
    | '/muscles/'
    | '/ver1/'
    | '/admin/muscles/$muscleId'
    | '/admin/muscles/import'
    | '/admin/recipes/$recipeId'
    | '/admin/recipes/import'
    | '/api/public/paddle-webhook'
    | '/ver1/admin/$'
    | '/admin/muscles/'
    | '/admin/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  MovementCheckRoute: typeof MovementCheckRoute
  MusclesRoute: typeof MusclesRouteWithChildren
  Ver1Route: typeof Ver1RouteWithChildren
  ApiCloudflareStreamWebhookRoute: typeof ApiCloudflareStreamWebhookRoute
  CheckoutCompleteRoute: typeof CheckoutCompleteRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement-check': {
      id: '/movement-check'
      path: '/movement-check'
      fullPath: '/movement-check'
      preLoaderRoute: typeof MovementCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles': {
      id: '/muscles'
      path: '/muscles'
      fullPath: '/muscles'
      preLoaderRoute: typeof MusclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ver1': {
      id: '/ver1'
      path: '/ver1'
      fullPath: '/ver1'
      preLoaderRoute: typeof Ver1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guides': {
      id: '/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminGuidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/cloudflare-stream-webhook': {
      id: '/api/cloudflare-stream-webhook'
      path: '/api/cloudflare-stream-webhook'
      fullPath: '/api/cloudflare-stream-webhook'
      preLoaderRoute: typeof ApiCloudflareStreamWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/complete': {
      id: '/checkout/complete'
      path: '/checkout/complete'
      fullPath: '/checkout/complete'
      preLoaderRoute: typeof CheckoutCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$programSlug': {
      id: '/library/$programSlug'
      path: '/$programSlug'
      fullPath: '/library/$programSlug'
      preLoaderRoute: typeof LibraryProgramSlugRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/account': {
      id: '/library/account'
      path: '/account'
      fullPath: '/library/account'
      preLoaderRoute: typeof LibraryAccountRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/muscles/': {
      id: '/muscles/'
      path: '/'
      fullPath: '/muscles/'
      preLoaderRoute: typeof MusclesIndexRouteImport
      parentRoute: typeof MusclesRoute
    }
    '/muscles/$muscleId': {
      id: '/muscles/$muscleId'
      path: '/$muscleId'
      fullPath: '/muscles/$muscleId'
      preLoaderRoute: typeof MusclesMuscleIdRouteImport
      parentRoute: typeof MusclesRoute
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ver1/': {
      id: '/ver1/'
      path: '/'
      fullPath: '/ver1/'
      preLoaderRoute: typeof Ver1IndexRouteImport
      parentRoute: typeof Ver1Route
    }
    '/ver1/admin': {
      id: '/ver1/admin'
      path: '/admin'
      fullPath: '/ver1/admin'
      preLoaderRoute: typeof Ver1AdminRouteImport
      parentRoute: typeof Ver1Route
    }
    '/admin/muscles/': {
      id: '/admin/muscles/'
      path: '/muscles'
      fullPath: '/admin/muscles/'
      preLoaderRoute: typeof AdminMusclesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/muscles/$muscleId': {
      id: '/admin/muscles/$muscleId'
      path: '/muscles/$muscleId'
      fullPath: '/admin/muscles/$muscleId'
      preLoaderRoute: typeof AdminMusclesMuscleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/muscles/import': {
      id: '/admin/muscles/import'
      path: '/muscles/import'
      fullPath: '/admin/muscles/import'
      preLoaderRoute: typeof AdminMusclesImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/': {
      id: '/admin/recipes/'
      path: '/recipes'
      fullPath: '/admin/recipes/'
      preLoaderRoute: typeof AdminRecipesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/$recipeId': {
      id: '/admin/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/admin/recipes/$recipeId'
      preLoaderRoute: typeof AdminRecipesRecipeIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/import': {
      id: '/admin/recipes/import'
      path: '/recipes/import'
      fullPath: '/admin/recipes/import'
      preLoaderRoute: typeof AdminRecipesImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/paddle-webhook': {
      id: '/api/public/paddle-webhook'
      path: '/api/public/paddle-webhook'
      fullPath: '/api/public/paddle-webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ver1/admin/$': {
      id: '/ver1/admin/$'
      path: '/$'
      fullPath: '/ver1/admin/$'
      preLoaderRoute: typeof Ver1AdminSplatRouteImport
      parentRoute: typeof Ver1AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminGuidesRoute: typeof AdminGuidesRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMusclesMuscleIdRoute: typeof AdminMusclesMuscleIdRoute
  AdminMusclesImportRoute: typeof AdminMusclesImportRoute
  AdminRecipesRecipeIdRoute: typeof AdminRecipesRecipeIdRoute
  AdminRecipesImportRoute: typeof AdminRecipesImportRoute
  AdminMusclesIndexRoute: typeof AdminMusclesIndexRoute
  AdminRecipesIndexRoute: typeof AdminRecipesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminGuidesRoute: AdminGuidesRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMusclesMuscleIdRoute: AdminMusclesMuscleIdRoute,
  AdminMusclesImportRoute: AdminMusclesImportRoute,
  AdminRecipesRecipeIdRoute: AdminRecipesRecipeIdRoute,
  AdminRecipesImportRoute: AdminRecipesImportRoute,
  AdminMusclesIndexRoute: AdminMusclesIndexRoute,
  AdminRecipesIndexRoute: AdminRecipesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LibraryRouteChildren {
  LibraryProgramSlugRoute: typeof LibraryProgramSlugRoute
  LibraryAccountRoute: typeof LibraryAccountRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryProgramSlugRoute: LibraryProgramSlugRoute,
  LibraryAccountRoute: LibraryAccountRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface MusclesRouteChildren {
  MusclesMuscleIdRoute: typeof MusclesMuscleIdRoute
  MusclesIndexRoute: typeof MusclesIndexRoute
}

const MusclesRouteChildren: MusclesRouteChildren = {
  MusclesMuscleIdRoute: MusclesMuscleIdRoute,
  MusclesIndexRoute: MusclesIndexRoute,
}

const MusclesRouteWithChildren =
  MusclesRoute._addFileChildren(MusclesRouteChildren)

interface Ver1AdminRouteChildren {
  Ver1AdminSplatRoute: typeof Ver1AdminSplatRoute
}

const Ver1AdminRouteChildren: Ver1AdminRouteChildren = {
  Ver1AdminSplatRoute: Ver1AdminSplatRoute,
}

const Ver1AdminRouteWithChildren = Ver1AdminRoute._addFileChildren(
  Ver1AdminRouteChildren,
)

interface Ver1RouteChildren {
  Ver1AdminRoute: typeof Ver1AdminRouteWithChildren
  Ver1IndexRoute: typeof Ver1IndexRoute
}

const Ver1RouteChildren: Ver1RouteChildren = {
  Ver1AdminRoute: Ver1AdminRouteWithChildren,
  Ver1IndexRoute: Ver1IndexRoute,
}

const Ver1RouteWithChildren = Ver1Route._addFileChildren(Ver1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  MovementCheckRoute: MovementCheckRoute,
  MusclesRoute: MusclesRouteWithChildren,
  Ver1Route: Ver1RouteWithChildren,
  ApiCloudflareStreamWebhookRoute: ApiCloudflareStreamWebhookRoute,
  CheckoutCompleteRoute: CheckoutCompleteRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
