/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovementCheckRouteImport } from './routes/movement-check'
import { Route as Ver1RouteImport } from './routes/ver1'
import { Route as Ver1IndexRouteImport } from './routes/ver1.index'
import { Route as Ver1AdminRouteImport } from './routes/ver1.admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementCheckRoute = MovementCheckRouteImport.update({
  id: '/movement-check',
  path: '/movement-check',
  getParentRoute: () => rootRouteImport,
} as any)
const Ver1Route = Ver1RouteImport.update({
  id: '/ver1',
  path: '/ver1',
  getParentRoute: () => rootRouteImport,
} as any)
const Ver1IndexRoute = Ver1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Ver1Route,
} as any)
const Ver1AdminRoute = Ver1AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => Ver1Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movement-check': typeof MovementCheckRoute
  '/ver1': typeof Ver1RouteWithChildren
  '/ver1/admin': typeof Ver1AdminRoute
  '/ver1/': typeof Ver1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movement-check': typeof MovementCheckRoute
  '/ver1/admin': typeof Ver1AdminRoute
  '/ver1': typeof Ver1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movement-check': typeof MovementCheckRoute
  '/ver1': typeof Ver1RouteWithChildren
  '/ver1/admin': typeof Ver1AdminRoute
  '/ver1/': typeof Ver1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movement-check' | '/ver1' | '/ver1/admin' | '/ver1/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movement-check' | '/ver1/admin' | '/ver1'
  id: '__root__' | '/' | '/movement-check' | '/ver1' | '/ver1/admin' | '/ver1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovementCheckRoute: typeof MovementCheckRoute
  Ver1Route: typeof Ver1RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement-check': {
      id: '/movement-check'
      path: '/movement-check'
      fullPath: '/movement-check'
      preLoaderRoute: typeof MovementCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ver1': {
      id: '/ver1'
      path: '/ver1'
      fullPath: '/ver1'
      preLoaderRoute: typeof Ver1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ver1/': {
      id: '/ver1/'
      path: '/'
      fullPath: '/ver1/'
      preLoaderRoute: typeof Ver1IndexRouteImport
      parentRoute: typeof Ver1Route
    }
    '/ver1/admin': {
      id: '/ver1/admin'
      path: '/admin'
      fullPath: '/ver1/admin'
      preLoaderRoute: typeof Ver1AdminRouteImport
      parentRoute: typeof Ver1Route
    }
  }
}

interface Ver1RouteChildren {
  Ver1AdminRoute: typeof Ver1AdminRoute
  Ver1IndexRoute: typeof Ver1IndexRoute
}

const Ver1RouteChildren: Ver1RouteChildren = {
  Ver1AdminRoute: Ver1AdminRoute,
  Ver1IndexRoute: Ver1IndexRoute,
}

const Ver1RouteWithChildren = Ver1Route._addFileChildren(Ver1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovementCheckRoute: MovementCheckRoute,
  Ver1Route: Ver1RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
