create table if not exists public.caption_workspaces (
  id uuid primary key default gen_random_uuid(),
  stream_uid text not null check (stream_uid ~ '^[a-f0-9]{32}$'),
  language text not null check (language in ('en', 'ko')),
  vtt text not null default 'WEBVTT\n',
  status text not null default 'draft' check (status in ('draft', 'review', 'published')),
  updated_at timestamptz not null default now(),
  unique (stream_uid, language)
);

create table if not exists public.caption_glossary (
  id bigint generated by default as identity primary key,
  source_term text not null,
  target_term text not null,
  note text not null default '',
  updated_at timestamptz not null default now(),
  unique (source_term)
);

alter table public.caption_workspaces enable row level security;
alter table public.caption_glossary enable row level security;

create policy "Admins manage caption workspaces"
  on public.caption_workspaces for all
  using (public.is_admin()) with check (public.is_admin());

create policy "Admins manage caption glossary"
  on public.caption_glossary for all
  using (public.is_admin()) with check (public.is_admin());

grant select, insert, update, delete on public.caption_workspaces to authenticated;
grant select, insert, update, delete on public.caption_glossary to authenticated;
grant usage, select on sequence public.caption_glossary_id_seq to authenticated;

create or replace function public.touch_caption_workspace()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists caption_workspaces_touch on public.caption_workspaces;
create trigger caption_workspaces_touch before update on public.caption_workspaces
for each row execute function public.touch_caption_workspace();
